### PR TITLE
Init setup

### PR DESCRIPTION
**Pull request by oneilh**
- VITE build tool setup
- JSON server dependency added
- initial project folder setup

### CODE REVIEW

**Comment by oneilh** [comment]
[PROJECT INITIALISATION](https://trello.com/c/EoDc0JIQ/15-project-initialisation)

**Review by Omoefe-Ugboma — COMMENTED** [review]
Did you guys agreed on using Vite? I thought it's create react app, we are using! Please kindly respond to this so as to move forward on this

**Comment by oneilh** [comment]
yes sir, we talked about yesterday

**Review by Omoefe-Ugboma — APPROVED** [review]
Alright that's fine, let's move on to the next stage of the project then. Everything is good on my side. Well done @oneilh

**Comment by oneilh** [comment]
yes sir

**Review by Iammteo — APPROVED** [review]
All seems good, Approved .

**Pull request merged**
