### PR TITLE
created custom layouts for webapp

### PR DESCRIPTION
**Pull request by Iammteo**

### CODE REVIEW

**Comment by oneilh** [comment]
you shld have also included the tailwind package you installed in the commit message

**Review by oneilh — APPROVED** [review]
already seen i just for me to pull and see the changes

**Comment by Iammteo** [comment]
i commented them in the App.jsx file so u can just copy and paste them in the terminal , i left a detailed instruction on how to do this there

**Review by Omoefe-Ugboma — APPROVED** [review]
Please kindly put a nice description next time.

**Pull request merged**
